name: smart_mirror_app
description: An app to control the Smart Mirror via bluetooth with smart_mirror_mcu firmware for esp32.
publish_to: 'none'
version: 0.0.0+0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true