name: smart_mirror_app
description: An app to control the Smart Mirror via bluetooth with smart_mirror_mcu firmware for esp32.
publish_to: 'none'
version: 0.1.2+0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  animations: ^2.0.7
  get: ^4.6.5
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy_Light.otf
          style: normal
          weight: 400
        - asset: assets/fonts/Gilroy_ExtraBold.otf
          style: normal
          weight: 700
    - family: UIcons
      fonts:
        - asset: assets/fonts/UIcons.ttf